package com.example.ap2_proyectofinal_angelraonel_joserafael.navigation

object Routes {
    const val LOGIN = "login_screen"
    const val ADMIN_HOME = "admin_home_screen"
    const val EMPLEADO_HOME = "empleado_home_screen"
    const val REGISTRO_CLIENTE = "registro_cliente_screen"
    const val CLIENTES_ADMIN = "clientes_admin_screen"
    const val CLIENTES_EMPLEADO = "clientes_empleado_screen"
    const val COBROS_ADMIN = "cobros_admin_screen"
    const val COBROS_EMPLEADO = "cobros_empleado_screen"
    const val RUTAS_ADMIN = "rutas_admin_screen"
    const val RUTAS_EMPLEADO = "rutas_empleado_screen"
    const val COBROS_RECIENTES = "cobros_recientes_screen"
    const val NOTIFICATIONS_ADMIN = "notifications_admin_screen"
    const val NOTIFICATIONS_EMPLEADO = "notifications_empleado_screen"
    const val EMPLOYEE_MANAGEMENT = "employee_management_screen"
    const val LOAN_APPROVAL = "loan_approval_screen"
    const val ADJUST_TARIFFS = "adjust_tariffs_screen"
    const val ADMIN_PROFILE = "admin_profile_screen"
    const val REGISTER_ADMIN = "register_admin_screen"
    const val CIERRE_CAJA = "cierre_caja_screen"
    const val REALIZAR_COBRO = "realizar_cobro_screen"
    const val EMPLEADO_PERFIL = "empleado_perfil_screen"
    const val ACTIVATION_CODE = "activation_code_screen"
}
